<?php
namespace frontend\widgets;

use yii\base\Widget;
use common\models\OsCategory;

class oscategoryWidget extends Widget {
    public $layoutType = 'standart';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $oscatHeader = OsCategory::find()->select('title, id, created_at')->orderBy('created_at ASC')->where(['status' => 1])->all();
        if ($this->layoutType == 'standart'){
            $view = 'oscategoryHeader';
        }

        return $this->render($view,[
            'oscatHeader' => $oscatHeader,
        ]);
    }
}