<?php
namespace frontend\widgets;

use yii\base\Widget;
use common\models\FilesSaid;

class osfilesWidget extends Widget {
    public $layoutType = 'standart';
    public $postCount = 8;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $osfile = FilesSaid::find()->select('name, image, id, description, os_file, created_at')->limit($this->postCount)->orderBy('created_at DESC')->where(['status' => 1])->all();
        if ($this->layoutType == 'standart'){
            $view = 'osfileindex';
            $postCount = 12;
        }
        elseif($this->layoutType == 'filessaid'){
            $view = 'filessaid';
        }

        return $this->render($view,[
            'osfiles' => $osfile,
        ]);
    }
}
