<?php
namespace frontend\widgets;

use Yii;
use yii\base\Widget;
use common\models\FilesSaid;
use common\models\FilessaidSearchCustom;

class SearchWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $searchModel = new FilessaidSearchCustom();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('searchView', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}