<?php
namespace frontend\widgets;

use yii\base\Widget;
use common\models\Wallpapers;

class wallpapersWidget extends Widget {
    public $layoutType = 'standart';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $wallpapers = Wallpapers::find()->select('name, image, id, created_at')->orderBy('created_at DESC')->all();
        if ($this->layoutType == 'standart'){
            $view = 'wallpapersView';
        }

        return $this->render($view,[
            'wallpapers' => $wallpapers,
        ]);
    }
}